export const projectsData = {
  'auto-call': {
    id: 'auto-call',
    title: 'AUTOcall',
    icon: '📱',
    description: '安卓手机批量拨打电话工具，高效自动化通话任务处理，支持批量管理与快捷操作。',
    fullDescription: 'AUTOcall 是一款基于 Kotlin 开发的 Android 自动化拨号工具。通过简洁的 UI 和强大的后台调度系统，用户可以批量导入电话号码，设置拨号间隔和重试策略，实现高效的通话任务自动化。适用于客户回访、通知提醒等场景。',
    tags: ['Kotlin', 'Android', 'Automation'],
    gradient: 'from-green-500/20 to-emerald-500/20',
    stars: 3,
    html_url: 'https://github.com/ZHCOOL520/AUTOcall',
    features: [
      '批量导入号码列表（CSV/TXT 支持）',
      '可配置拨号间隔和重试次数',
      '通话记录自动保存与统计',
      '后台服务持续运行',
      '简洁 Material Design 界面',
    ],
    techStack: [
      { name: 'Kotlin', desc: '核心开发语言' },
      { name: 'Android Jetpack', desc: '架构组件' },
      { name: 'Material Design', desc: 'UI 设计规范' },
      { name: 'Android Telephony API', desc: '通话控制' },
    ],
    readmeSummary: 'AUTOcall 是一款实用的 Android 自动化拨号工具。项目结构清晰，采用 Kotlin + Jetpack 架构，支持从 CSV/TXT 文件批量导入号码，可灵活配置拨号间隔、重试次数等参数。适用于需要批量拨打电话的业务场景。',
  },
  'echomusic-pluginst': {
    id: 'echomusic-pluginst',
    title: 'EchoMusicPluginst',
    icon: '🎵',
    description: 'EchoMusic 的非官方插件仓库，主打神人。为音乐爱好者提供丰富的插件扩展与个性化功能。',
    fullDescription: 'EchoMusicPluginst 是 EchoMusic 音乐播放器的非官方插件集合仓库。收录了 10+ 款实用插件，涵盖歌词显示、频谱可视化、界面动效、封面处理等功能。每个插件独立打包，用户可按需安装。所有插件均与官方版本无关联，属社区贡献。',
    tags: ['JavaScript', 'EchoMusic', 'Plugin'],
    gradient: 'from-purple-500/20 to-pink-500/20',
    stars: 1,
    html_url: 'https://github.com/ZHCOOL520/EchoMusicPluginst',
    features: [
      'dynamic-island-lyric — 灵动岛歌词',
      'water-lyrics — 水波纹歌词特效',
      'page-motion — 页面过渡动画',
      'scroll-assistant — 滚动辅助',
      'cover-fallback — 封面回退',
      'lyric-info-scroll — 歌词信息滚动',
      'spectrum-visualizer — 频谱可视化',
      'webdav-music — WebDAV 音乐源',
      'echomusic-vinyl-rotation — 黑胶唱片旋转',
      'lyrics-bridge — 歌词桥接',
      'echo-miuix-plugin — MIUIX 主题',
    ],
    techStack: [
      { name: 'JavaScript', desc: '插件开发语言' },
      { name: 'EchoMusic API', desc: '播放器接口' },
      { name: 'CSS', desc: '视觉效果与动画' },
      { name: 'WebDAV', desc: '云音乐源' },
    ],
    readmeSummary: '本仓库收录 EchoMusic 播放器的 10+ 款非官方插件。涵盖灵动岛歌词(dynamic-island-lyric)、水波纹特效(water-lyrics)、频谱可视化(spectrum-visualizer)、黑胶旋转(echomusic-vinyl-rotation)、MIUIX 主题等实用功能。支持在线安装和本地安装两种方式。MIT 开源协议。',
  },
  'mccraft-launcher': {
    id: 'mccraft-launcher',
    title: 'HarmonyOS-McCraftLaucher',
    icon: '🎮',
    description: '基于 HarmonyOS 的 Minecraft 启动器，为鸿蒙生态打造的原生游戏启动与管理工具。',
    fullDescription: 'McCraftLauncher 是专为 HarmonyOS NEXT（鸿蒙）打造的 Minecraft 启动器。充分利用鸿蒙原生能力和 ArkUI 框架，提供原生级的游戏启动体验。支持多版本管理、横竖屏自适应、Material Design 风格 UI，是鸿蒙生态中 Minecraft 游戏的重要基础设施。',
    tags: ['C++', 'HarmonyOS', 'Minecraft'],
    gradient: 'from-orange-500/20 to-red-500/20',
    stars: 2,
    html_url: 'https://github.com/ZHCOOL520/HarmonyOS-McCraftLaucher',
    features: [
      '原生鸿蒙 NEXT 游戏启动体验',
      '横竖屏自适应布局',
      '多 Minecraft 版本管理',
      '现代化 Material Design UI',
      '游戏动态资讯展示',
      '版本设置与版本切换',
      'Launcher Logo 和启动动画',
      '平板/手机多设备适配',
    ],
    techStack: [
      { name: 'C++ (ArkTS NAPI)', desc: '核心原生逻辑' },
      { name: 'ArkUI', desc: '声明式 UI 框架' },
      { name: 'DevEco Studio', desc: '鸿蒙 IDE' },
      { name: 'HarmonyOS SDK API 12+', desc: '系统接口' },
    ],
    readmeSummary: '基于 HarmonyOS NEXT 开发的 Minecraft 启动器。采用原生 C++ + ArkTS 混合架构，支持多版本游戏管理、Material Design UI、横竖屏自适应。使用 DevEco Studio 开发，目标 SDK API 12+。MIT 开源协议。作者 ZHCOOL520，B站：space.bilibili.com/1414910921。',
  },
  'harmonyos-autocall': {
    id: 'harmonyos-autocall',
    title: 'HarmonyOS-AUTOcall',
    icon: '📲',
    description: 'AUTOcall 的 HarmonyOS 移植版，将批量拨号功能带到鸿蒙平台，MIT 开源协议。',
    fullDescription: 'HarmonyOS-AUTOcall 是 AUTOcall 的鸿蒙移植版本。基于 ArkTS 语言和 ArkUI 框架重写，完整实现了批量拨号、通话录音、音频播放、文件导入、SIM 卡选择等核心功能。通过 NAPI 桥接调用系统电话 API，是 Android 到鸿蒙跨平台移植的优秀实践案例。',
    tags: ['TypeScript', 'HarmonyOS', 'MIT'],
    gradient: 'from-blue-500/20 to-cyan-500/20',
    stars: 1,
    html_url: 'https://github.com/ZHCOOL520/HarmonyOS-AUTOcall',
    features: [
      '批量拨号（call.makeCall API）',
      '通话状态监听（observer 模块）',
      '通话录音（AVRecorder）',
      '音频播放（AVPlayer）',
      'CSV/TXT 文件导入号码列表',
      'SIM 卡选择（默认卡/SIM1/SIM2/双卡）',
      '拨号间隔可配置（1-10秒）',
      '通话中音频播放/录音',
      '通话统计与排版功能',
    ],
    techStack: [
      { name: 'ArkTS (TypeScript)', desc: '核心开发语言' },
      { name: 'ArkUI', desc: '声明式 UI' },
      { name: 'HarmonyOS Telephony', desc: '通话 API' },
      { name: 'HarmonyOS Media', desc: '音频录制播放' },
      { name: 'hvigor', desc: '构建工具' },
    ],
    readmeSummary: 'AUTOcall 的 HarmonyOS NEXT 移植版。使用 ArkTS (TypeScript 超集) 重写，完整实现 Android 版的批量拨号功能，包括通话状态监听(observer)、录音(AVRecorder)、音频播放(AVPlayer)、CSV/文本导入、SIM 选择等。构建工具使用 hvigor，目标 HarmonyOS API 9+。MIT 开源协议。',
  },
  lolipickaxe: {
    id: 'lolipickaxe',
    title: 'LoliPickaxe-1.20.1AI',
    icon: '⛏️',
    description: 'Minecraft 1.20.1 版本的 AI 增强模组，为游戏带来智能化的新玩法与交互体验。',
    fullDescription: 'LoliPickaxe 是一个 Minecraft 1.20.1 Forge 模组。正在从 1.12.2 版本迁移中，添加了多种有趣的功能武器系统、方块系统、配方系统、附魔系统和网络数据同步。包含 24+ 种物品、自定义 GUI/Container、实体渲染增强等。是 Java Forge 模组开发的综合实践项目。',
    tags: ['Java', 'Minecraft', 'AI', 'Mod'],
    gradient: 'from-rose-500/20 to-pink-500/20',
    stars: 2,
    html_url: 'https://github.com/ZHCOOL520/LoliPickaxe-1.20.1AI',
    features: [
      '24+ 种自定义武器/工具',
      '3 个自定义方块',
      '自定义配方系统',
      '附魔系统（新附魔效果）',
      'GUI 和 Container 系统',
      '自定义实体与渲染',
      '网络数据包同步（Network Handling）',
      '客户端-服务端分离架构',
      '事件监听与拦截',
    ],
    techStack: [
      { name: 'Java 17', desc: 'Minecraft 运行环境' },
      { name: 'Minecraft Forge 47.2+', desc: '模组加载器' },
      { name: 'Gradle', desc: '构建系统' },
      { name: 'Mojang Mappings', desc: '源码映射' },
    ],
    readmeSummary: '基于 Minecraft 1.20.1 + Forge 47.2 的综合模组项目。从 1.12.2 迁移中（约35%完成度），已完成物品系统(24个)、方块系统(3个)、配方系统、附魔系统、GUI/Container、网络通信框架等。使用 Java 17 + Gradle 构建。MIT 开源协议。作者原 ID：Is_GK。',
  },
};
