export const skillsData = {
  kotlin: {
    id: 'kotlin',
    title: 'Kotlin',
    icon: '🟣',
    color: '#7F52FF',
    level: 88,
    category: '编程语言',
    description: 'Kotlin 是一种运行在 JVM 上的现代静态类型编程语言，由 JetBrains 开发。它简洁、安全、与 Java 完全互操作，是 Android 官方推荐的一级开发语言。',
    scenarios: [
      'Android 原生应用开发（Google 官方首选语言）',
      'HarmonyOS 应用开发（通过 Kotlin Multiplatform）',
      '后端服务开发（Ktor、Spring Boot）',
      '跨平台移动开发（Kotlin Multiplatform Mobile）',
      '自动化脚本与工具开发',
    ],
    features: [
      '空安全（Null Safety）消除 NPE 风险',
      '协程（Coroutines）简化异步编程',
      '扩展函数增强代码可读性',
      '数据类（Data Class）自动生成通用方法',
      '与 Java 100% 互操作，可混编',
    ],
    links: [
      { name: 'Kotlin 官方文档', url: 'https://kotlinlang.org/docs/home.html' },
      { name: 'Kotlin Playground', url: 'https://play.kotlinlang.org/' },
      { name: 'Android Kotlin 指南', url: 'https://developer.android.com/kotlin' },
    ],
    relatedProjects: ['auto-call'],
  },
  java: {
    id: 'java',
    title: 'Java',
    icon: '☕',
    color: '#ED8B00',
    level: 82,
    category: '编程语言',
    description: 'Java 是最流行的面向对象编程语言之一，以其"一次编写，到处运行"的跨平台特性闻名。在 Minecraft Mod 开发和企业级应用领域有着不可替代的地位。',
    scenarios: [
      'Minecraft Forge/Fabric Mod 开发',
      'Minecraft 服务端插件开发（Bukkit/Spigot/Paper）',
      '企业级后端开发（Spring 生态）',
      'Android 应用开发（传统）',
      '大数据处理（Hadoop、Spark）',
    ],
    features: [
      'JVM 跨平台，一次编译到处运行',
      '成熟的生态系统和海量第三方库',
      '强类型静态语言，编译期错误检查',
      '优秀的 IDE 支持（IntelliJ IDEA）',
      '庞大的开发者社区',
    ],
    links: [
      { name: 'Java 官方文档', url: 'https://docs.oracle.com/en/java/' },
      { name: 'Minecraft Forge 文档', url: 'https://docs.minecraftforge.net/' },
      { name: 'PaperMC 插件开发', url: 'https://docs.papermc.io/paper/dev' },
    ],
    relatedProjects: ['lolipickaxe'],
  },
  cpp: {
    id: 'cpp',
    title: 'C++',
    icon: '🔵',
    color: '#00599C',
    level: 78,
    category: '编程语言',
    description: 'C++ 是一种高性能的通用编程语言，广泛应用于系统级开发、游戏引擎、嵌入式系统和需要极致性能的场景。在 HarmonyOS 原生开发中扮演重要角色。',
    scenarios: [
      'HarmonyOS Native 开发（NAPI 接口）',
      '游戏引擎开发（Minecraft 启动器底层）',
      '跨平台桌面应用（Qt 框架）',
      '高性能计算与图形渲染',
      '嵌入式系统与 IoT 设备',
    ],
    features: [
      '极致性能，接近底层硬件',
      'STL 标准模板库提供丰富数据结构',
      'RAII 资源管理机制',
      '多范式编程支持（面向对象、泛型、函数式）',
      '现代 C++（C++17/20）大幅提升开发体验',
    ],
    links: [
      { name: 'C++ Reference', url: 'https://en.cppreference.com/' },
      { name: 'HarmonyOS Native 开发', url: 'https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/napi-introduction' },
      { name: 'LearnCpp 教程', url: 'https://www.learncpp.com/' },
    ],
    relatedProjects: ['mccraft-launcher'],
  },
  typescript: {
    id: 'typescript',
    title: 'TypeScript',
    icon: '🔷',
    color: '#3178C6',
    level: 80,
    category: '编程语言',
    description: 'TypeScript 是 JavaScript 的类型化超集，由微软开发。它添加了静态类型系统，大幅提升了大型项目的可维护性和开发体验。在 HarmonyOS ArkTS 开发中是核心技术栈。',
    scenarios: [
      'HarmonyOS ArkTS 应用开发',
      '大型前端项目架构',
      'Node.js 后端服务开发',
      '跨平台应用（React Native、Electron）',
      '库和框架开发（类型定义）',
    ],
    features: [
      '静态类型检查，减少运行时错误',
      '智能 IDE 自动补全与重构',
      'ESNext 特性提前使用',
      '接口和泛型提供强大抽象能力',
      '与 JavaScript 生态完美兼容',
    ],
    links: [
      { name: 'TypeScript 官方文档', url: 'https://www.typescriptlang.org/docs/' },
      { name: 'ArkTS 开发指南', url: 'https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/arkts-get-started' },
      { name: 'TypeScript Playground', url: 'https://www.typescriptlang.org/play' },
    ],
    relatedProjects: ['harmonyos-autocall'],
  },
  javascript: {
    id: 'javascript',
    title: 'JavaScript',
    icon: '🟡',
    color: '#F7DF1E',
    level: 85,
    category: '编程语言',
    description: 'JavaScript 是 Web 开发的核心语言，也是全球最流行的编程语言之一。在 EchoMusic 插件开发和 Web 全栈领域有广泛应用。',
    scenarios: [
      'EchoMusic 插件开发',
      'Web 前端开发（React、Vue）',
      'Node.js 服务端开发',
      '浏览器扩展开发',
      '自动化脚本与爬虫',
    ],
    features: [
      '动态类型，灵活快速开发',
      '事件驱动与非阻塞 I/O',
      'NPM 全球最大的包管理生态',
      'ES6+ 现代语法糖',
      '全栈统一语言（前后端同构）',
    ],
    links: [
      { name: 'MDN JavaScript 文档', url: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript' },
      { name: 'Node.js 官方文档', url: 'https://nodejs.org/docs/latest/' },
      { name: 'JavaScript.info 教程', url: 'https://javascript.info/' },
    ],
    relatedProjects: ['echomusic-pluginst'],
  },
  android: {
    id: 'android',
    title: 'Android',
    icon: '🤖',
    color: '#34A853',
    level: 90,
    category: '平台 & 生态',
    description: 'Android 是全球最大的移动操作系统平台。熟练掌握 Android 原生开发，包括 Kotlin/Java 编程、Jetpack 组件库和系统级 API 调用。',
    scenarios: [
      '原生 Android 应用开发',
      '系统级自动化工具（批量拨号等）',
      'Android Framework 定制',
      '跨平台方案中的原生桥接',
    ],
    features: [
      'Kotlin 一等公民 + Java 兼容',
      'Jetpack Compose 现代 UI 框架',
      '强大的权限与后台任务管理',
      'Google Play 全球分发',
    ],
    links: [
      { name: 'Android 开发者官网', url: 'https://developer.android.com/' },
      { name: 'Kotlin Android 开发', url: 'https://developer.android.com/kotlin' },
    ],
    relatedProjects: ['auto-call'],
  },
  harmonyos: {
    id: 'harmonyos',
    title: 'HarmonyOS',
    icon: '🔶',
    color: '#FF6B35',
    level: 80,
    category: '平台 & 生态',
    description: 'HarmonyOS（鸿蒙）是华为自主研发的分布式操作系统。熟悉 ArkTS 语言、ArkUI 框架和 NAPI 原生接口，具备从 Android 到鸿蒙的跨平台移植经验。',
    scenarios: [
      'HarmonyOS NEXT 原生应用开发',
      'Android 应用移植到鸿蒙平台',
      'NAPI 原生 C++ 模块开发',
      '分布式设备协同开发',
    ],
    features: [
      'ArkTS 语言（TypeScript 超集）',
      'ArkUI 声明式 UI 框架',
      'NAPI 桥接原生 C++ 能力',
      '一次开发多设备部署',
      '系统级安全与隐私保护',
    ],
    links: [
      { name: 'HarmonyOS 开发者官网', url: 'https://developer.huawei.com/consumer/cn/harmonyos/' },
      { name: 'ArkTS 开发文档', url: 'https://developer.huawei.com/consumer/cn/doc/harmonyos-guides/arkts-get-started' },
      { name: 'DevEco Studio', url: 'https://developer.huawei.com/consumer/cn/deveco-studio/' },
    ],
    relatedProjects: ['mccraft-launcher', 'harmonyos-autocall'],
  },
  'minecraft-forge': {
    id: 'minecraft-forge',
    title: 'Minecraft Forge',
    icon: '⚒️',
    color: '#8B4513',
    level: 78,
    category: '平台 & 生态',
    description: 'Minecraft Forge 是最流行的 Minecraft Java 版模组加载器。通过 Forge 可以深度修改游戏机制，添加新物品、方块、实体和自定义系统。',
    scenarios: [
      'Minecraft 模组（Mod）开发',
      '游戏机制扩展与自定义',
      '服务端插件与客户端模组联调',
      '跨版本 API 迁移适配',
    ],
    features: [
      '完整的 Minecraft 源码映射（MCP/Mojang Mappings）',
      '事件总线系统（EventBus）',
      '注册表系统（Registry）管理物品/方块',
      '网络数据包自定义（Network Handling）',
      'Gradle 构建系统集成',
    ],
    links: [
      { name: 'Minecraft Forge 文档', url: 'https://docs.minecraftforge.net/' },
      { name: 'Forge 社区论坛', url: 'https://forums.minecraftforge.net/' },
    ],
    relatedProjects: ['lolipickaxe'],
  },
  'minecraft-mod': {
    id: 'minecraft-mod',
    title: 'Minecraft Mod',
    icon: '⛏️',
    color: '#8B4513',
    level: 80,
    category: '创作领域',
    description: 'Minecraft Mod 开发涉及 Java 编程、游戏机制理解和创意设计。能够独立完成从概念设计到发布的全流程 Mod 开发。',
    scenarios: [
      '自定义武器/工具/方块开发',
      'AI 行为增强系统',
      'GUI 和 Container 系统',
      '配方与附魔系统定制',
      '网络同步与数据包处理',
    ],
    features: [
      '完整的游戏开发管线经验',
      '事件驱动架构设计',
      '客户端-服务端通信',
      '材质与模型自定义',
    ],
    links: [
      { name: 'McJty Modding 教程', url: 'https://wiki.mcjty.eu/modding/' },
      { name: 'Forge 官方文档', url: 'https://docs.minecraftforge.net/' },
    ],
    relatedProjects: ['lolipickaxe'],
  },
  'minecraft-plugin': {
    id: 'minecraft-plugin',
    title: 'Minecraft Plugin',
    icon: '📦',
    color: '#D4A574',
    level: 75,
    category: '创作领域',
    description: 'Minecraft 服务端插件开发基于 Bukkit/Spigot/Paper API，可以为服务器添加自定义功能、小游戏和管理工具。',
    scenarios: [
      '服务端功能扩展',
      '小游戏开发',
      '管理工具插件',
      'EchoMusic 服务端音乐插件',
    ],
    features: [
      '事件监听与拦截',
      '命令注册系统',
      '配置文件和持久化',
      '与客户端模组配合',
    ],
    links: [
      { name: 'PaperMC 文档', url: 'https://docs.papermc.io/paper/dev' },
      { name: 'SpigotMC 插件开发', url: 'https://www.spigotmc.org/wiki/spigot-plugin-development/' },
    ],
    relatedProjects: ['echomusic-pluginst'],
  },
};
